### ISSUE TITLE
patches overwritten https://github.com/guqinchen/OpenPLC_v3

### ISSUE THREAD

**Issue by boonpin1975** [thiagoralves/OpenPLC_v3#108]
I unzip the file from https://github.com/guqinchen/OpenPLC_v3 , but every time I run sudo ./install.sh linux , the files from https://github.com/guqinchen/OpenPLC_v3 was overwritten .

**Comment by innir** [comment]
You are referring to a different repository, you probably better go there and file bugs.

**Comment by thiagoralves** [comment]
This is probably because the installer from guqinchen is pulling the files from the official repository (which is this one). You will have to fix this with guqinchen.
