### ISSUE TITLE
CPACK

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#11]
Investigate using Cpack to make binaries and installers, eg .deb files

https://cmake.org/cmake/help/v3.0/module/CPack.html

https://nowardev.wordpress.com/2009/12/27/how-to-create-a-debian-package-for-script-and-for-project-that-use-cmake/

**Comment by thiagoralves** [comment]
I'll close this for now until there is more progress on the subject...
