### ISSUE TITLE
Add hardware layer for Revolution Pi

### ISSUE THREAD

**Issue by innir** [thiagoralves/OpenPLC_v3#122]
@thiagoralves how about adding the hardware layer for the [Revolution Pi](https://revolution.kunbus.com/?noredirect=en_US) you posted in the [forum](https://openplc.discussion.community/post/revolutionpi-support-10181282?pid=1310066356)?

**Comment by thiagoralves** [comment]
As I said in the forum, I'll only add it to the repository once I have testers reporting that it actually works
