### ISSUE TITLE
where are openplc logs stored, i.e if I am reading a register , there is no log, are there any logs generated for the protocol activity tool using tools like mbtget or modbuspal

### ISSUE THREAD

**Issue by adityasriv22** [thiagoralves/OpenPLC_v3#123]

**Comment by thiagoralves** [comment]
PLCs don’t generate logs. Since OpenPLC tries to mimic the behavior of general PLCs, it has no log either. It shouldn’t be hard to implement that feature yourself. Check /webserver/core/modbus.cpp. You should be able to implement a log mechanism between the modbus calls
