### ISSUE TITLE
Matiec compiler not terminating

### ISSUE THREAD

**Issue by FranzJosephII** [thiagoralves/OpenPLC_v3#127]
When compiling the following structured text code the matiec compiler seems to be stuck in an endless loop (Ubuntu 19.10):

CONFIGURATION _$ RESOURCE F$_ ON _6 TASK Y_W ( SINGLE := %QL 1_ . BYTE # 3_4 , PRIORITY := 16#__e ) ; END_RESOURCE VAR_ACCESS _ : ON : TIME READ_ONLY ; END_VAR END_CONFIGURATION

**Comment by innir** [comment]
You should probably file matiec bugs at the matiec bug tracker: https://bitbucket.org/mjsousa/matiec/

OpenPLC is just using matiec as a translator from ST to C++

**Comment by FranzJosephII** [comment]
Filed the bug there - thanks!
