### ISSUE TITLE
Error connection with Modbus

### ISSUE THREAD

**Issue by vickymadeshwaran** [thiagoralves/OpenPLC_v3#129]
I am trying to control LED using Arduino Uno. In Editor i used to swap the function with not gate. Created two coils for input and output. i am trying in linux platform please help me with any sample projects with arduino uno in linux.

**Comment by mjimm** [comment]
Hi, take a look at the opening tutorial - it shows how to take contact inputs and drive a coil output connected to an LED.  https://www.openplcproject.com/reference-your-first-project

Also there's the forum :)  https://openplc.discussion.community/

Hope this helps
