### ISSUE TITLE
install.sh swapfile

### ISSUE THREAD

**Issue by EDVTAZ** [thiagoralves/OpenPLC_v3#13]
Hello @thiagoralves ,

I've been using OpenPLC with the rpi3 and everything worked nicely. But today I tried to install it on another one and the install script failed. I noticed that there was a swapfile among the files, that wasn't there on the other rpi3. After looking through the install script, I found the lines that create the swapfile. I removed them and OpenPLC installed nicely. Basically, there wasn't enough space on my SD card for the swapfile, but there was enough for OpenPLC.

Is there any particular reason for creating the swapfile? If no, I would suggest removing these lines, or if yes, I think it should be made conditional and skipped if there isn't enough disk space to create them. If you agree, I would be happy create a pull request with whatever solution we come up with.

**Comment by pedromorgan** [comment]
would be interesting to look at CPACK to make pre-compiled binaries..
