### ISSUE TITLE
Update python version

### ISSUE THREAD

**Issue by u2n** [thiagoralves/OpenPLC_v3#139]
Every time install routine calls python (U20.04/deb), deprecation notice prints:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

**Comment by thiagoralves** [comment]
OpenPLC needs a big rewrite to be compatible with Python 3. Since I don't have time to do it myself, I'm closing the issue until I find someone willing to fix it.

**Comment by KieranTHE** [comment]
> 
> 
> OpenPLC needs a big rewrite to be compatible with Python 3. Since I don't have time to do it myself, I'm closing the issue until I find someone willing to fix it.

Hadn't seen this one. How much is there to be re written?
