### ISSUE TITLE
docker run failed with docker error: Error response from daemon: OCI runtime create failed:./start_openplc.sh: no such file or directory: unknown.

### ISSUE THREAD

**Issue by songku** [thiagoralves/OpenPLC_v3#161]
I followed the installation guide on https://github.com/thiagoralves/OpenPLC_v3 on my ubuntu 20.04.1,and I have installed through `./install.sh linux`.I also build on docker throuth `docker build -t openplc:v3 `.
The above procedure worked well until I execute:`docker run -it --rm --privileged -p 8080:8080 openplc:v3` with the following wrong message: 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./start_openplc.sh": stat ./start_openplc.sh: no such file or directory: unknown.
However,I  can start webui by `cd ../OpenPLC_v3/webserver`,and execute `./start_openplc.sh`.It shows that the webui have been started on localhost:8080 and I can login in.
How can I fix this problem?Do I need to install agin from the beginning?

**Comment by songku** [comment]
I fix this problem by drag the start_openplc.sh file to the higher level of the folder, which contains the webserver.py and it works well.

**Comment by jay-jjwu** [comment]
@songku , hi i got the same issue as you mentioned above, but i cannot find the /start_openplc.sh in latest master branch. Where is this file?
thanks for support!

**Comment by songku** [comment]
> @songku , hi i got the same issue as you mentioned above, but i cannot find the /start_openplc.sh in latest master branch. Where is this file? thanks for support!

It's been a long time since my last comment and I don't do much about this work now.I'm worried my suggestion below may not work well.
I think the file `start_openplc.sh` is inside the container.You can try to search for this file inside your openplc container.

**Comment by jay-jjwu** [comment]
@songku , thanks for your reply.
Finally, i modify the dockerfile as mentioned by this post, and it works now! 
Just fyi.
https://openplc.discussion.community/post/openplc-v-3-stoptimizer-and-iec2c-problem-12604935#:~:text=I'm%20using%20the%20software%20in%20a%20docker%20container.
