### ISSUE TITLE
Trying to load blinky program on to chinese MEGA 2560 board

### ISSUE THREAD

**Issue by BikiniBottomsVeryOwn** [thiagoralves/OpenPLC_v3#202]
I tried loading blinky onto my offbrand MEGA 2560 board from AliExpress.  

Got this error when I tried to upload program to board via the default Arduino Mega setting:

plc_prog.st:3-5..3-28: error: Bit size of data type is incompatible with bit size of location.
1 error(s) found. Bailing out!
Error: Couldn't find LOCATED_VARIABLES.h. Check iec2c compiler output for more information

**Comment by BikiniBottomsVeryOwn** [comment]
I also mapped the blink variable (bool) to pin number 2 on the mega which is an analog output.

**Comment by thiagoralves** [comment]
As the error clearly tells you, but size of data (BOOL) is incompatible with bit size of location (INT). You cannot assign an analog output to a BOOL variable.
