### ISSUE TITLE
OpenPLC Runtime on Windows 11 installed via standard download & install - Not able to spin up webserver

### ISSUE THREAD

**Issue by BikiniBottomsVeryOwn** [thiagoralves/OpenPLC_v3#203]
I'm getting this error when trying to open OpenPLC Runtime via clicking on its icon in Windows.

![image](https://user-images.githubusercontent.com/38847726/232197266-a5af204f-a0d5-4e21-8a85-ef73e516d82a.png)

![image](https://user-images.githubusercontent.com/38847726/232197310-2765bca2-80bc-4729-b84c-9e663039ba9d.png)

**Comment by thiagoralves** [comment]
0.0.0.0 means "all interfaces". If running  on the same machine you should go to 127.0.0.1
