### ISSUE TITLE
Windows runtime installer does not work

### ISSUE THREAD

**Issue by jm-andonegi** [thiagoralves/OpenPLC_v3#205]
The [Windows runtime installer](https://openplcproject.com/docs/installing-openplc-runtime-on-windows/)  should install cygwin, but when I try to install it on Windows 10 I get an error saying that cygwin is not installed.

There is another method to install it manually but it would be helpful to do it with a single installer.

Thanks for this great project :)

**Comment by thiagoralves** [comment]
I would need more information on that to understand what the issue is. Most likely a proxy or other network setting is preventing cygwin donwload.
