### ISSUE TITLE
Problems with some hardware on Linux

### ISSUE THREAD

**Issue by bascetta74** [thiagoralves/OpenPLC_v3#207]
Selecting as hardware "Simulink" there is a compilation issue as the runtime (though it is running on a Linux machine) tries to compile for windows, the same happens selecting "Blank".

In my opinion there is a mistake in OpenPLC_v3/webserver/scripts/change_hardware_layer.sh at lines 17 and 80:
    echo win > ../scripts/openplc_platform
that should instead be
    echo linux > ../scripts/openplc_platform

**Comment by thiagoralves** [comment]
That’s why there is an option for Simulink for Linux only. Same applies for Blank.
