### ISSUE TITLE
run openopc runtime ,cannot access  http://0.0.0.0:8080/

### ISSUE THREAD

**Issue by seriousuncle** [thiagoralves/OpenPLC_v3#212]
Verifying Runtime Installation...
cp: 无法获取'/workdir/webserver/dnp3_default.cfg' 的文件状态(stat): No such file or directory
cp: 无法获取'/workdir/webserver/openplc_default.db' 的文件状态(stat): No such file or directory
 * Serving Flask app "webserver" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)

**Comment by thiagoralves** [comment]
1. Open browser
2. Type http://localhost:8080
