### ISSUE TITLE
/workdir doesn't exist

### ISSUE THREAD

**Issue by glennra** [thiagoralves/OpenPLC_v3#213]
https://github.com/thiagoralves/OpenPLC_v3/blob/dcaaea46cc977c2063ef59f5817f430947e51dd6/webserver/scripts/start_openplc.sh#L8C65-L8C65

On neuron this script gets copied into the OpenPLC_v3 installation directory and is called by the systemd unit.  /workdir doesn't exist. Should this have been substituted for the installation dir by the installer script?

**Comment by glennra** [comment]
Also the *default* files referenced in this script are missing, or the script needs to be updated to reflect the proper names.

**Comment by Fengbujue862** [comment]
I got the same probelm. have you fix it?

**Comment by didididididididididid** [comment]
me too
