### ISSUE TITLE
LD VAR block unable to read or write to subvariables within Stuctures

### ISSUE THREAD

**Issue by Gaantry** [thiagoralves/OpenPLC_v3#214]
When working with the VAR block within a Ladder Diagram, the variable properties dialogue box doesn't include any of the sub-variables within a user defined data structure. I am able to interact with sub-variables via structured text, but not from a LD it seems.

**Comment by thiagoralves** [comment]
Can you give a specific example? What can you access on ST that you can’t on LD?

**Comment by Gaantry** [comment]
I seem to have gotten ahead of myself, apologies
