### ISSUE TITLE
Fix Python Dependency versions

### ISSUE THREAD

**Issue by shrmrf** [thiagoralves/OpenPLC_v3#22]
@thiagoralves what is your opinion on fixing the Python dependencies through a `requirements.txt` file?

This way we won't break if for instance the Flask project has some changes in the latest version. We can just issue a `pip install -r requirements.txt` command for installation of the dependencies.

I can submit a PR if you're interested.

**Comment by pedromorgan** [comment]
@shrmrf yep..

**Comment by pedromorgan** [comment]
Also we need to consider python3 (although need to check flask etc)

**Comment by shrmrf** [comment]
@pedromorgan sure... Python 2 is going out in 2020 so not a bad idea :)

**Comment by thiagoralves** [comment]
I think the requirements.txt file is a good idea. I saw that you made the modification only on the Docker install. Would you mind modifying it for all the other platforms as well? We might just need to make sure it will work under Cygwin (Windows) as well...

About python3, have you tried just running it plain in python3 to see what happens? I still haven't, but it may be worth trying

**Comment by thiagoralves** [comment]
In fact, I'm starting to get a bit worried about this. Github notified me after I accepted the requirements.txt file that it is using pycrypto <= 2.6.1 and there are security issues about that. In that sense, having pip install downloading the latest version of packages might be a good idea. Maybe we should keep the requirements.txt file as a backup in case something breaks in the future...

**Comment by shrmrf** [comment]
Another perspective:

>In fact, I'm starting to get a bit worried about this. Github notified me after I accepted the requirements.txt file that it is using pycrypto <= 2.6.1 ...

This I would say is an advantage of using `requirements.txt`.. GitHub can understand and parse this file. Otherwise, we'd never know of a vulnerability even though it was there. ([more on this from GitHub's blog](https://github.blog/2018-07-12-security-vulnerability-alerts-for-python/#how-to-start-using-python-security-alerts)

**Comment by shrmrf** [comment]
FYI: I did a bit of investigation and figured that `pycrypto==2.6.1` is installed by just installing `python` and `python-pip` i.e. `sudo apt install python python-pip`

Thus, I think removing it in the PR #24 was the correct idea. 

Sorry again for the alarm I caused.
