### ISSUE TITLE
(Stable) releases

### ISSUE THREAD

**Issue by serpent213** [thiagoralves/OpenPLC_v3#224]
Just a question, I can't find any revisions tagged as stable, the development branch is not in use any more apparently.

Is latest master always expected to be stable? For a PLC runtime that's quite an important point, I dare say.  🙂

**Comment by thiagoralves** [comment]
Yes, master is always the stable release. After the migration of the Python 3 branch to the master branch, development on this editor has slowed down as the attention is now focused on the new editor: https://github.com/Autonomy-Logic/openplc-editor

**Comment by thiagoralves** [comment]
The new runtime is pretty much a work in progress. It is not usable at all right now, and most of the development has been on the webserver architecture.
