### ISSUE TITLE
No License Present

### ISSUE THREAD

**Issue by David-Kopczynski** [thiagoralves/OpenPLC_v3#257]
# Problem
I have seen initiatives for GPL or Apache licensing #17, #71, [OpenPLC Licensing](https://openplc.discussion.community/post/openplc-licensing-12728601), [License of OpenPLC Runtime for Linux](https://openplc.discussion.community/post/license-of-openplc-runtime-for-linux-10059730), and [OpenPLC Runtime Change of License ](https://openplc.discussion.community/post/openplc-runtime-change-of-license-12595882) but can't seem to find any work in the `master` branch. (*The `development` branch looks right but has been abandoned #224 long ago.*) 

Many people (*including me*) have been using this software in some form with the false sense of security of "Open Source". This especially holds true, as [instructions for installation](https://autonomylogic.com/docs/installing-openplc-runtime-on-linux-systems/) are provided. However, without any clear `LICENSE` file this project is legally speaking not allowed to be used, modified, or shared. 

Sadly, this fact has only come to my awareness after I have spent time with it in my work. While I could just use it, this is at my own risk **and without any proper way of publishing my own repository working with OpenPLC as intended before**.

## Possible Solution
Licensing issues can be resolved by adding a proper `LICENSE` file. As [OpenPLC_v2](https://github.com/thiagoralves/OpenPLC_v2) and [OpenPLC](https://github.com/thiagoralves/OpenPLC) use GPL-3.0, and parts of this repository are also licenced under a form of GPL, I recommend the use of GPL as well.

**Comment by thiagoralves** [comment]
Thanks for pointing this out. Added GPLv3 license to the project.
