### ISSUE TITLE
Windows CI Pipeline

### ISSUE THREAD

**Issue by shrmrf** [thiagoralves/OpenPLC_v3#28]
@pedromorgan and @thiagoralves 
As we discussed in #14 and #26 we should consider a CI pipeline on Windows as well. I know for a fact that appveyor is the most popular CI tool for Windows builds but I personally have no experience with it.

If it's fine with you guys, can we start an experiment in my fork to add appveyor support?

Or, maybe @pedromorgan do you know of any other (free) CI option for Windows?

**Comment by pedromorgan** [comment]
Well at least the rpi job succeded.. https://gitlab.com/openplcproject/openplc_v3/-/jobs/157437170

the cygwin needs tweaking i think

**Comment by shrmrf** [comment]
@pedromorgan does Gitlab also have the option of running Windows builds? (that'd be awesome)

**Comment by pedromorgan** [comment]
Its running a cygwin build https://gitlab.com/openplcproject/openplc_v3/-/jobs/157437169

**Comment by shrmrf** [comment]
May I suggest using the official raspbian image for the rpi?: https://hub.docker.com/r/raspbian/jessie

**Comment by pedromorgan** [comment]
@shrmrf umm https://gitlab.com/openplcproject/openplc_v3/-/jobs/157463721

**Comment by pedromorgan** [comment]
@thiagoralves Whats your gitlab user ??

**Comment by shrmrf** [comment]
>@shrmrf umm https://gitlab.com/openplcproject/openplc_v3/-/jobs/157463721

:confused:  I guess we should revert. Sorry about that :(

**Comment by thiagoralves** [comment]
I don't have a gitlab user yet. Will create an account soon, just in the
middle of a big mess right now...

**Comment by pedromorgan** [comment]
@shrmrf I'll look at it later..

Also setup a temp chat room here https://gitter.im/openPLCProjectx/community

**Comment by shrmrf** [comment]
This container (`teaci/cygwin64`) isn't a Windows container: https://gitter.im/openPLCProjectx/community?at=5c5b44e68790df06206de3b2

I think appveyor is our last hope

**Comment by pedromorgan** [comment]
It looks like appveyor in tergrated with gitlab.. just trying to figure out the yml file format..

**Comment by pedromorgan** [comment]
somethings like this https://gitlab.com/inkscape/inkscape/blob/master/.appveyor.yml
