### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#3]
Am looking at the webserver code.

Can I suggest using templating (eg [Jinja2](http://jinja.pocoo.org/docs/2.10/) is popular), as this would make things easier.

I can implement if the maintainers think its a good idea.

**Comment by pedromorgan** [comment]
am hacking away, jinja2 is built in to flask as default template engine..

**Comment by thiagoralves** [comment]
I'll close this for now until there is more progress on the subject...
