### ISSUE TITLE
new www server

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#36]
Hi @thiagoralves 

Got some time so hacking away at last part of www server merge.. #3 

Am also looking at dumping sqlite and using files instead (json etc)

You mention csv files for storage,
so for hacking purposes do u have a few samples or the format ??

**Comment by pedromorgan** [comment]
ok so revisiting again and wanting to help here are some objectives

1) moving to gitlab so we can use the CI stuff and mainly doxygen to generate docs from source...
- we can move main "origin"  there and "push updates" to gitthub

2) I'll finish up the new www server (last step is the javascript. sigh!)

2++) remove sqlite, and move to yaml, toml, csv whatever is easier....
- we are assuming this is in a lab, so maybe login can be easier or not at all (eg localhost)

3) Generate doxygen from source files 

4) Make openplcproject.com in markdown as documentation and publish on openplcproject.gitlab.com = same

**Comment by pedromorgan** [comment]
Step #5..
Setup a testing framework, so as to use upstream libs + versions..eg modbus and get problem matrix

**Comment by thiagoralves** [comment]
I don’t have anything in mind, you can use csv, json, whatever you feel like is better.

**Comment by pedromorgan** [comment]
what u mentioned before is "most use csv" is my curious...
ie 
- a heading and col defs
- and rows of data

**Comment by pedromorgan** [comment]
I kinda want to split out stuff.. into seperate repos..

eg a "platforms" repos
- and its assosiated platform as directories and binding..

This will make CI testing much easier

**Comment by pedromorgan** [comment]
MIDI = Music digital interface...(should be easy to attach sound and alike to events ? kick snare etc)
there is a ridim in a machine
So we should be able to "synthesize" a machine and sound.  eg...
(trust me, am 53+ years and hot engineer with a s.600 sapler, and sbx80. timecode machine)

**Comment by garretfick** [comment]
Looks like the www server is coming back alive. I'm running into a few things with the existing www server that are making me less efficient and wanted to know if it is worthwhile addressing or just wait.

I know I'm new to this project (and so my thoughts should be appropriately weighted as near zero), but I would prioritize on splitting things up rather than moving Gitlab. You can generate docs, do tests, etc, all with Gitlab.

**Comment by pedromorgan** [comment]
I get the felling I might the temp PA and coder for now..

But indeed a list o stuff to do..

Splitting up the project is what u want to do..
and the ONLY ONLY reason for gitlab.. is the pages/
and in CI can knock that stuff API  and alike as a "job" on a VM

If u are new o this realm, as i but some other experience, then cool...

>

**Comment by garretfick** [comment]
I think you might have replied to the wrong person :)

**Comment by pedromorgan** [comment]
@garretfick unfortunately notes to onself.. 

My PA temp is gitlab-ci and alike ..
https://gitlab.com/openplcproject
https://openplcproject.gitlab.io/openplc_v3/

If we can get cmake to gen the doxygen then cool ;-)

**Comment by pedromorgan** [comment]
https://gitter.im/openPLCProjectx/community

**Comment by pedromorgan** [comment]
see #59 for server in golang instead ;-)

**Comment by pedromorgan** [comment]
aww #69
