### ISSUE TITLE
cmake builds

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#58]
Just notice that there's a cmake of gluegenerator.. 
so being a muppet to cmake kinda

```
mkdir build/glue_evo
cd build/glue_evo
cmake ../../utils/glue_generator_src/
``` 
and it compiled ;-))
but ended up up with 2 files
```
utils/glue_generator_src/bin/glue_generator
utils/glue_generator_src/bin/glue_generator_test
```

So it works..
Main question is whats strategic plan ??

**Comment by pedromorgan** [comment]
I then run 
```
mkdir new_build_space
cd new_build_space
cmake ../OpenPLC_v3
make
```
and crashed with (umm gonna push build to gitlab)

**Comment by pedromorgan** [comment]
https://gitlab.com/openplcproject/openplc_v3/pipelines

Yipee.. got loads of emails..

**Comment by garretfick** [comment]
This has now been committed and is in development.

**Comment by pedromorgan** [comment]
yipee :-) and thanks.. supervisor.coder.it.and.all from bottom
