### ISSUE TITLE
golang

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#6]
Ok so this might be crazy..

But the more I dig into the code,
I realise there is a lot of comms stuff.. and alike
going on etc etc..

This smacks of what golang is good at, concurrency, multi things going on, websockets et all..

Would be intrigued to start a project as altername, for fun of course

**Comment by pedromorgan** [comment]
reasons..

its static types, so no cock up on stuff..

**Comment by pedromorgan** [comment]
Be interesting ultimately to create a single page app..
with websockets and background ajax..

Am also developing a NativeScript app for mobile, so kinda r+d there also

**Comment by pedromorgan** [comment]
Ok so working on golang version, for my curious...

**Comment by thiagoralves** [comment]
I'll close this for now until there is more progress on the subject...
