### ISSUE TITLE
Open PLC future

### ISSUE THREAD

**Issue by pedromorgan** [thiagoralves/OpenPLC_v3#7]
Ok so hacked a bit,
and finding where the project is at..
and helping with a future..
so am adding ideas and issues in this thread. for fun

**Comment by pedromorgan** [comment]
@thiagoralves am exited about this project.. and a free weekend.. ;-)))

So mainly I want to help in
- documentation (am familiar)
- www dev (day job)
- others.. am adding ass issues

**Comment by pedromorgan** [comment]
Documentation
----------------------------

Its a complex project with c++, py, sh et all..
To skin the cos cat,
I suggest firing doxygen at the source..

A

**Comment by thiagoralves** [comment]
Issue #8 discuss this already
