### ISSUE TITLE
on Pi, TOF delayed at switch-off physical PI pin

### ISSUE THREAD

**Issue by jancumps** [thiagoralves/OpenPLC_v3#78]
When using the Hello World example on a Raspberry Pi 3B, Linux raspberrypi 4.14.98-v7+ #1200,
when executing the example, the output %QX0.0 nicely switches off after 2 seconds in the OpenPLC Monitoring page.
The physical pin 8 on the PI connector stays 3.3V for various time between 2 and 11 seconds though, before returning to 0V level.

**Comment by thiagoralves** [comment]
Make sure you don't have any other process (including Serial, i2c or SPI configuration) trying to control that pin. Its always recommended to install OpenPLC on a clean Raspbian image
