### ISSUE TITLE
Two BYTE number ADD, do not supprot!

### ISSUE THREAD

**Issue by xinsuinizhuan** [thiagoralves/OpenPLC_v3#84]
I add two BYTE number, compile it, it errors.

**Comment by innir** [comment]
True, as this operation is not defined in the IEC 61131-3. -> no bug.

BTW: OpenPLC uses matiec to compile IEC 61131-3 code to C. If you think you found bugs in the language implementation, better file bugs against matiec: https://bitbucket.org/mjsousa/matiec/src/default/
