### ISSUE TITLE
It does not supprot implicit type conversion!

### ISSUE THREAD

**Issue by xinsuinizhuan** [thiagoralves/OpenPLC_v3#86]
I code below snapshot, compile it ,errors.
![1565859863(1)](https://user-images.githubusercontent.com/40679769/63084900-d7463d80-bf7e-11e9-916d-969691e36f48.jpg)

**Comment by thiagoralves** [comment]
This is not C or python, this is IEC 61131-3 Structured Text programming. The standard defines a strictly typed language, which means that there shouldn't be any implicit type conversion.
