### ISSUE TITLE
Do you hava test the newest MatIEC？

### ISSUE THREAD

**Issue by xinsuinizhuan** [thiagoralves/OpenPLC_v3#87]
When i use the newest MatIEC， some problem, as when i have a st that include a functionblock variable， the error line is add to 1，when i have two functionblock variable, the error line is add 2.
like my st file, could you help me?
[plc_1.zip](https://github.com/thiagoralves/OpenPLC_v3/files/3504968/plc_1.zip)
[plc_2.zip](https://github.com/thiagoralves/OpenPLC_v3/files/3504969/plc_2.zip)

**Comment by innir** [comment]
Works for me with no problem.
